import { Container, Footer, Navbar } from '@/components'
import { Geist } from 'next/font/google'
import localFont from "next/font/local";
import './globals.css'

export const metadata = {
  title: 'Rashid Machingal',
  description: 'Generated by create next app',
}

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geist = Geist({ subsets: ['latin'], weights: [400, 500, 600, 700, 800],  })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}  >
        <Container>
          <Navbar/>
         {children}
         <Footer/>
        </Container>
      </body>
    </html>
  )
}
