import { Container, Footer, Navbar } from '@/components'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rashid Machingal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Navbar/>
         {children}
         <Footer/>
        </Container>
      </body>
    </html>
  )
}
