import { Container, Footer, Navbar } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Rashid Machingal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Navbar/>
         {children}
         <Footer/>
        </Container>
      </body>
    </html>
  )
}
