import { Main, Hero, Navbar, About } from '../src/components'
import Head from 'next/head'

export default function Home() {
  return (
    <div className='container' >
      <Head>
        <title>Rashid Machingal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
       <Navbar/>
       <Hero/>
       <About/>
      </Main>

    </div>
  )
}
