import Head from 'next/head'
import Navbar from '../src/components/Navbar/Navbar'
import Hero from '../src/components/Hero/Hero'

export default function Home() {
  return (
    <div className='container' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className='main_white_box' >
      <Navbar/>
      <Hero/>
    </div>

    </div>
  )
}
