import { Hero, About, BlogSectionHome, ProjectsHome } from '../src/components'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rashid Machingal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Hero/>
       <About/>
       <ProjectsHome/>
       <BlogSectionHome/>
    </>
  )
}
